service: new-channel-notify-slack

custom:
  defaultStage: dev
  api_version: v0
  common: common # serverless.ymlのバグ回避用

provider:
  name: aws
  runtime: provided
  timeout: 300
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: qazx7412
  environment:
    ${file(./env.yml)}

functions:
  notify_slack:
    handler: notify_slack
    events:
      - http:
          path: notify_slack
          method: post
          integration: lambda
